version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: formwang_dev
      POSTGRES_USER: formwang
      POSTGRES_PASSWORD: formwang123
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db_data: